
import random
speed(0)
penup()
setposition(random.randint(-150, 150), random.randint(-150, 150))
pendown()
def next_circle():
    left(270)
    penup()
    forward(25)
    pendown()
    left(90)
radius=25
for i in range (4):
    circle(radius)
    radius += 25
    next_circle()
penup()
setposition(-754, -723)
dart_color_one = input("What color of darts do you want player 1?  ")
dart_color_two = input("what color of darts do you want player 2?  ")
print("player 1")
dart_x = int(input("try to hit the center! on X "))
dart_y= int(input("try to hit the center! on Y  "))
penup()
print("player 2")
dart_a = int(input("try to hit the center! on X "))
dart_z= int(input("try to hit the center! on Y  "))
penup()
color(dart_color_one)
setposition(dart_x, dart_y+3)
pendown()
begin_fill()
circle(6)
end_fill()
penup()
color(dart_color_two)
setposition(dart_x, dart_y-3)
pendown()
begin_fill()
circle(6)
end_fill()
penup()
setposition(990, 909)
